### ISSUE TITLE
Feature request - onLetter,bool for imperfect diagonal,hint coloring

### ISSUE THREAD

**Issue by pazelisha** [Amonc/crossword#10]
Hey, I had a few ideas : 
1. onLetter function that records the current letter painted so we can make ourselves a widget similiar to the upper text between "names" and the grid : 
https://github.com/Amonc/crossword/assets/74504869/7a1dd531-33d4-4b4e-b3b8-3b2b366c7fe2

2. A boolean for turning off the imperfect diagonal line feature as described in (saw your reaction on it) :  https://github.com/Amonc/crossword/issues/6

3. a function that draws on one of the letters based on a given (row,col) to give a hint like : 
https://github.com/Amonc/crossword/assets/74504869/d7060f35-f78b-433f-9918-db952ce1b575

Hope you will consider those ideas, I think it will make the package much more complete.
Enjoying the package a lot ! Thank you guys.

**Comment by Amonc** [comment]
@pazelisha 

-  Use to render words realtime while line is being drawn  
```
onLineUpdate: (String word) {
                    setState(() {
                      this.word = word;
                    });
                  },
``` 
- I couldn't find any quick solution to disable the imperfect line, I added a faded color as default. Colors can be customized:

```  invalidLineColors: [Colors.red.withOpacity(0.1)]```

- Added a slight animate and decoration to control the speed and animate factors

```check example```

Thanks a lot for sharing ideas. Happy Coding!!!
