### ISSUE TITLE
Feature Request - Add way to highlight already found words

### ISSUE THREAD

**Issue by SedemGarr** [Amonc/crossword#13]
Hi there! I love your amazing work and would like to use your plugin in my application https://play.google.com/store/apps/details?id=com.wayyyoutgames.simple_word_search. 

However, my app allows users to save and resume their progress and I cannot find a way to highlight words that a user has already found in a previous session. Is there a way to make this possible? Or does the feature already exist?

Thanks again for the amazing work. All the best!

**Comment by Amonc** [comment]
@SedemGarr  Added following support to the [Crossword v1.1.0](https://pub.dev/packages/crossword/versions/1.1.0)

- `initialLineList`: Accepts a `List` of `LineOffset` to add initial lines to the crossword 
--  A `LineOffset` is a class that takes the `start` and `end` positions of the line
