### ISSUE TITLE
Bug: Displayed Matrix cannot be updated

### ISSUE THREAD

**Issue by Aquarius-blake** [Amonc/crossword#3]
I created a function to generate a new matrix of letters with new words inserted each time a specific button is pressed. However the Crossword widget only displays the first data it received , it does not update the matrix when a new matrix is generated. I already checked the value of the matrix from console and it gets updated, but the displayed matrix maintains the first matrix generated on the app start.

**Comment by Amonc** [comment]
Thanks a lot, @Aquarius-blake ⚡️⚡️

**Comment by Aquarius-blake** [comment]
You are welcome 👍👍
