### ISSUE TITLE
line Indicator moves away from the perfect CrossLine

### ISSUE THREAD

**Issue by AneesSelinei** [Amonc/crossword#6]
Good job on the puzzle-solving user interface.

I noticed there's a glitch when swiping across the line; sometimes, the visual indicator skips the cross line, either going up or down.

**Comment by Amonc** [comment]
@AneesSelinei Could you add any screen recording to demonstrate the issue in more depth?

**Comment by AneesSelinei** [comment]
Uploading Screenrecorder-2024-01-15-09-40-44-463(0).mp4…

**Comment by AneesSelinei** [comment]
@Amonc 

This behavior makes it difficult to swipe cross words.

https://github.com/Amonc/crossword/assets/55734339/042f8f8b-ec4e-44e8-9b1f-6e42ac191574

**Comment by AneesSelinei** [comment]
@Amonc  
This behavior makes it difficult to swipe cross words.

https://github.com/Amonc/crossword/assets/55734339/0f5ee583-5d32-44ce-9dec-0c9cf00d64a2

**Comment by AneesSelinei** [comment]
@Amonc 
 This behavior makes it difficult to swipe  the cross words.

https://github.com/Amonc/crossword/assets/55734339/8b7a0f02-0011-402e-8e2a-912ae14f5c5b

**Comment by Amonc** [comment]
@AneesSelinei This is not a bug or glitch.  We intentionally added it to deselect a line while selecting through the wrong letters.

**Comment by AneesSelinei** [comment]
![Screenshot 2024-01-29 211638](https://github.com/Amonc/crossword/assets/55734339/bcf1ebbd-7a69-471b-b6ec-a6122e3e120e)


@Amonc  I apologize, but I fail to see this crossed line as a feature because it clearly does not highlight the letters I swiped.

**Comment by pazelisha** [comment]
can we disable this type of behavior ? if i drag to a cross line and then moves 1 step it creates an illegal line, also while drawing the line it makes an illegal line (as mentioned in this issue)
