### ISSUE TITLE
How to allow drawing of lines on word only when it matches a given word

### ISSUE THREAD

**Issue by defemz** [Amonc/crossword#8]
Hello and thanks for this great plugin. 
I want to implement a flutter code where colored lines will not be allowed to be drawn on the Crossword widget if the selected word does not match one of the pre selected list of words, or if the selected word does not make sense. I noticed that every time a user draw lines across the Crossword widget, the lines got drawn even when the word over which the line is drawn does not make sense. I want to be able to check the selected word(the word across which a line is drawn) against a list of words, stored in a list. The following is what i have done so far:

```
Crossword(
        letters: letters,
        spacing: const Offset(30, 30),
        onLineDrawn: (List<String> words) {
          print(words);
        },
        textStyle: const TextStyle(color: Colors.white, fontSize: 20),
        lineDecoration:
        LineDecoration(lineColors: lineColors, strokeWidth: 20),
        hints: const ["GOOD", "GREAT", "ALLOY", "ANNOYING"],
        allowOverlap: true,
      )
```

**Comment by Amonc** [comment]
@defemz  I released a new version [Crossword 0.0.7](https://pub.dev/packages/crossword) and added the fix for this one. 

Please consider using ` addIncorrectWord: false,` inside the `Crossword` widget to fulfil your criteria.
